from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

class Stretcher:
    def __init__(
        self,
        sample_rate: int,
        channels: int,
        time_ratio: float,
        pitch_scale: float,
        option_flags: int,
    ) -> None: ...
    def study(self, audio: NDArray[np.float32], final: bool = False) -> None: ...
    def process(self, audio: NDArray[np.float32], final: bool = False) -> None: ...
    def reset(self) -> None: ...
    def set_time_ratio(self, ratio: float) -> None: ...
    def set_pitch_scale(self, scale: float) -> None: ...
    def set_formant_scale(self, scale: float) -> None: ...
    def set_transients_option(self, options: int) -> None: ...
    def set_detector_option(self, options: int) -> None: ...
    def set_phase_option(self, options: int) -> None: ...
    def set_formant_option(self, options: int) -> None: ...
    def set_pitch_option(self, options: int) -> None: ...
    def get_time_ratio(self) -> float: ...
    def get_pitch_scale(self) -> float: ...
    def get_formant_scale(self) -> float: ...
    def get_preferred_start_pad(self) -> int: ...
    def get_start_delay(self) -> int: ...
    def get_latency(self) -> int: ...
    def get_channel_count(self) -> int: ...
    def set_expected_input_duration(self, samples: int) -> None: ...
    def set_max_process_size(self, samples: int) -> None: ...
    def get_process_size_limit(self) -> int: ...
    def get_samples_required(self) -> int: ...
    def available(self) -> int: ...
    def retrieve(self) -> NDArray[np.float32]: ...

def metadata(
    sample_rate: int,
    channels: int,
    time_ratio: float,
    pitch_scale: float,
    option_flags: int,
) -> dict[str, int | float]: ...
def stretch_float32(
    audio: NDArray[np.float32],
    sample_rate: int,
    time_ratio: float,
    pitch_scale: float,
    option_flags: int,
) -> NDArray[np.float32]: ...
