from __future__ import annotations

class Stretcher:
    def __init__(
        self,
        sample_rate: int,
        channels: int,
        time_ratio: float,
        pitch_scale: float,
        option_flags: int,
    ) -> None: ...
    def study(self, audio: object, final: bool = False) -> None: ...
    def process(self, audio: object, final: bool = False) -> None: ...
    def reset(self) -> None: ...
    def set_time_ratio(self, ratio: float) -> None: ...
    def set_pitch_scale(self, scale: float) -> None: ...
    def set_formant_scale(self, scale: float) -> None: ...
    def set_transients_option(self, options: int) -> None: ...
    def set_detector_option(self, options: int) -> None: ...
    def set_phase_option(self, options: int) -> None: ...
    def set_formant_option(self, options: int) -> None: ...
    def set_pitch_option(self, options: int) -> None: ...
    def get_time_ratio(self) -> float: ...
    def get_pitch_scale(self) -> float: ...
    def get_formant_scale(self) -> float: ...
    def get_preferred_start_pad(self) -> int: ...
    def get_start_delay(self) -> int: ...
    def get_latency(self) -> int: ...
    def get_channel_count(self) -> int: ...
    def set_expected_input_duration(self, samples: int) -> None: ...
    def set_max_process_size(self, samples: int) -> None: ...
    def get_process_size_limit(self) -> int: ...
    def get_samples_required(self) -> int: ...
    def available(self) -> int: ...
    def retrieve(self) -> object: ...
    def get_engine_version(self) -> int: ...
    def set_key_frame_map(self, key_frames: dict[int, int]) -> None: ...
    def get_frequency_cutoff(self, n: int) -> float: ...
    def set_frequency_cutoff(self, n: int, frequency: float) -> None: ...
    def get_input_increment(self) -> int: ...
    def get_output_increments(self) -> list[int]: ...
    def get_phase_reset_curve(self) -> list[float]: ...
    def get_exact_time_points(self) -> list[int]: ...
    def set_debug_level(self, level: int) -> None: ...
    @staticmethod
    def set_default_debug_level(level: int) -> None: ...

class LiveShifter:
    def __init__(
        self,
        sample_rate: int,
        channels: int,
        option_flags: int,
    ) -> None: ...
    def reset(self) -> None: ...
    def set_pitch_scale(self, scale: float) -> None: ...
    def set_formant_scale(self, scale: float) -> None: ...
    def get_pitch_scale(self) -> float: ...
    def get_formant_scale(self) -> float: ...
    def get_start_delay(self) -> int: ...
    def get_channel_count(self) -> int: ...
    def set_formant_option(self, options: int) -> None: ...
    def get_block_size(self) -> int: ...
    def shift(self, audio: object) -> object: ...
    def shift_into(self, audio: object, output: object) -> None: ...
    def set_debug_level(self, level: int) -> None: ...
    @staticmethod
    def set_default_debug_level(level: int) -> None: ...

def metadata(
    sample_rate: int,
    channels: int,
    time_ratio: float,
    pitch_scale: float,
    option_flags: int,
) -> dict[str, int | float]: ...
def stretch_float32(
    audio: object,
    sample_rate: int,
    time_ratio: float,
    pitch_scale: float,
    option_flags: int,
) -> object: ...
def option_constants() -> dict[str, int]: ...
